spring:
  application:
    name: account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/account_db
    password: E15@root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: '8081'

account:
  msg: This is Account microservice for Bank application - QA profile
  build-version: 1
