spring:
  application:
    name: card
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/card_db
    password: E15@root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: '8082'
